spring:
  application:
    name: eureka-client
server:
  port: 7777

#服务注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: *
