spring:
  application:
    name: user
server:
  port: 4444

say-hellos:
  ribbon:
    eureka:
      enabled: false
  listOfServers: localhost:5555,localhost:5556,localhost:5557,localhost:5558
  ServerListRefreshInterval: 15000
